services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017/code-dojo-db
  db:
    image: "mongo"
    environment:
      MONGO_INITDB_DATABASE: code-dojo-db
    ports:
      - "27017:27017"
